### ISSUE TITLE
More Inputs

### ISSUE THREAD

**Issue by mablze** [cgierke/homebridge-musiccast#10]
Hi, is it possible to add more input options such as:
- Optical
- Coaxial
- Phono
- CD
- Line 1
- Line 2
- Line 3

Best Regards
Mark

**Comment by cgierke** [comment]
Hi Mark, you can add any available input to your config ([example in readme.md](https://github.com/cgierke/homebridge-musiccast/blob/main/README.md)). The exact input names depend on your specific Yamaha device, you can query the complete `input_list` of supported inputs for your device like this: [http://\<ip-of-your-yamaha-device\>/YamahaExtendedControl/v1/system/getFeatures](http://<<ip-of-your-yamaha-device>>/YamahaExtendedControl/v1/system/getFeatures).
