### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by mablze** [cgierke/homebridge-musiccast#11]
Could you also please add a simple  switch button wich link and unlink  wireless MusicCast speakers with the musiccast amplifier?![image](https://github.com/user-attachments/assets/60e3699b-6043-4b20-9735-fc7ceb754091)

**Comment by cgierke** [comment]
Hi Mark, I'm sorry, but to keep the Apple Home App buttons simple, the plugin always links all speakers - you can only set their volume or turn them on or off.
