### ISSUE TITLE
Error on plugin start - Yamaha MusicCast BAR 40 

### ISSUE THREAD

**Issue by CezaryCiosek** [cgierke/homebridge-musiccast#3]
Hi, 

I have a problem with your plugin. Could you tell me what should I do to add plugin to homebridge? Screen + config below.
 
![Zrzut ekranu 2023-05-23 o 12 54 46](https://github.com/cgierke/homebridge-musiccast/assets/110975881/6bd6c255-3a6f-445d-900f-5af9cb0f5959)

`{
            "name": "MusiccastMultiroom",
            "server": {
                "host": "192.168.x.xx",
                "volumePercentageLow": 25,
                "volumePercentageHigh": 65
            },
            "platform": "MusiccastMultiroom",
            "_bridge": {
                "username": "0E:CB:8D:xx:xx:xx:xx",
                "port": 59092
            }
        }
`

**Comment by cgierke** [comment]
It seems you’re missing the `clients` config, the plugin currently doesn’t work for a single server device without connected clients.

**Comment by CezaryCiosek** [comment]
thank you very much. Adding client speaker solved the problem :)
