### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by mcfmichielsen** [cgierke/homebridge-musiccast#6]
Hi,

Not sure since when or how exactly, but the musiccast plugin is no longer working for me.
The following is appearing in the homebridge logs 

 [20/11/2023, 13:23:58] [Musiccast] invalid config TypeError: Cannot read properties of undefined (reading 'map')
    at new MusiccastMultiroom (/var/lib/homebridge/node_modules/homebridge-musiccast-multiroom/src/main.ts:43:41)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:150:42)

I hope someone can assist?

**Comment by cgierke** [comment]
this looks like a config error, can you post your json config for the plugin here?

**Comment by pavelvlodarczyk** [comment]
Hi,
I have similar error - version v0.2.8

> invalid config TypeError: Cannot read properties of undefined (reading 'map')
>     at new MusiccastMultiroom (/var/lib/homebridge/node_modules/homebridge-musiccast-multiroom/src/main.ts:52:41)
>     at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:150:42)

Section 'Client' is required or optional? Because after I delete this section and go back to edit, the section 'Client' autocomplete with IP 192.0.2.22.

My config:
```
{
    "name": "Yamaha RX-V6A",
    "server": {
        "host": "192.168.1.228",
        "volumePercentageLow": 25,
        "volumePercentageHigh": 65,
        "inputs": [
            {
                "input": "hdmi1",
                "name": "Apple TV"
            },
            {
                "input": "hdmi2",
                "name": "PS5"
            },
            {
                "input": "hdmi4",
                "name": "TV"
            },
            {
                "input": "tuner",
                "name": "Radio"
            },
            {
                "input": "airplay",
                "name": "AirPlay"
            }
        ]
    },
    "platform": "MusiccastMultiroom"
}

**Comment by pavelvlodarczyk** [comment]
If I add same address IP (AV) to Clients there is another error. I don't have another Multicast Client, only AV so I think Client should be optional.

`Error: Accessory RX-V6A experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by pavelvlodarczyk** [comment]
Temporary solution is to add empty array in clients properties directly in JSON configuration:

or modify line 52 in main.ts

```
{
    "name": "Yamaha RX-V6A",
    "server": {
        "host": "192.168.1.228",
        "volumePercentageLow": 25,
        "volumePercentageHigh": 65,
        "inputs": [
            {
                "input": "hdmi1",
                "name": "Apple TV"
            },
            {
                "input": "hdmi2",
                "name": "PS5"
            },
            {
                "input": "hdmi4",
                "name": "TV"
            },
            {
                "input": "tuner",
                "name": "Radio"
            },
            {
                "input": "airplay",
                "name": "AirPlay"
            }
        ]
    },
    "clients": [],
    "platform": "MusiccastMultiroom"
}

**Comment by pavelvlodarczyk** [comment]
Apart from that above it seems to work in Apple Home app iOS 17.3.1 :) AV -> RX-V6A

After bridge is added there is info in widget log to add accessories manually:
> Please add [RX-V6A DE26] manually in Home app (+). Setup Code: XXX-XX-XXX 

It would be better if accessories will be added right after bridge is configured in Apple Home app

@cgierke nice job!

**Comment by cgierke** [comment]
> Temporary solution is to add empty array in clients properties directly in JSON configuration

@pavelvlodarczyk thanks for figuring that out, I will make the config handling more resilient in a future release!

**Comment by cgierke** [comment]
fixed in https://github.com/cgierke/homebridge-musiccast/releases/tag/v0.2.10, `"clients"` section is now optional
