### ISSUE TITLE
Zone2 support

### ISSUE THREAD

**Issue by Kadibuntu** [cgierke/homebridge-musiccast#7]
Currently a RX-A1050 with Main zone = living room and zone2 = kitchen is running in our home.
It would be nice if you could add a zone support to your wonderful plugin :-)
An on/off switch of the main-sync for zone2 would be nice!
Maybe with a volume control and an off toggle switch in settings (when leaving home) 
Thanks again for your plugin!

**Comment by mablze** [comment]
It would be great to have another block when we could change zones:
A
B
A+B

**Comment by cgierke** [comment]
I don't have multiple zones at home, so I can't really build this myself 😅
