### ISSUE TITLE
Add Scene as Input

### ISSUE THREAD

**Issue by mrxxxxxx** [cgierke/homebridge-musiccast#8]
Hallo,

Thanks for the plugin, so far it works as it should. Is it also possible to add scenes as input?

**Comment by cgierke** [comment]
I just checked the Yamaha documentation: scenes are not inputs - but there is a way to change scenes in the Yamaha API. I will think about adding that in the future!

**Comment by mrxxxxxx** [comment]
That would be great. what about Siri control, what is already possible? Volume, input change? Thank you

**Comment by cgierke** [comment]
I couldn't add scenes to the input selector, as scenes can be triggered with the Yamaha API, but it seems there is no way to find out which scene is currently selected.
