### ISSUE TITLE
Clients not linking when activated via HomeKit scene

### ISSUE THREAD

**Issue by pssturges** [cgierke/homebridge-musiccast#9]
Hi. Finding this plugin really useful. It is particularly useful for use in HomeKit scenes. However, when the server and several clients are activated at the same time via a scene, often the clients don't link. I think this may due to the server not being ready when clients try to connect. Would  it be possible to try adding a short delay before clients try to connect? Thanks

**Comment by cgierke** [comment]
Thanks! I’m actually annoyed by the same problem and have been thinking about how to fix it, probably I will add some automatic retry mechanism.

**Comment by pssturges** [comment]
Ok Great. Yeah was thinking something like that may be another way to fix it.

**Comment by cgierke** [comment]
The latest [release 0.2.11](https://github.com/cgierke/homebridge-musiccast/releases/tag/v0.2.11) finally waits until a device confirms a specifc state (for example: power on) before it triggers the next action (for example: link a device). I hope that helps here as well!

**Comment by pssturges** [comment]
Awesome. Thanks!
